### ISSUE TITLE
[Sub-Issue] Jackson 직렬화 시 null 데이터 제외 (기본 직렬화 inclusion condition: non_null)

### ISSUE THREAD

**Issue by merge-simpson** [merge-simpson/demo-multimodule#58]
### 이슈 내용

Jackson 설정에서 기본 직렬화 inclusion condition을 `non_null`로 합니다.

### 부연 설명

예를 들어 다음 작업이 가능합니다.

<br />

```yaml
spring:
  jackson:
    default-property-inclusion: non_null
```
